namespace: blitzball

backend:
  image: blitzball-backend
  tag: 0.1.0
  servicePort: 8000
  env:
    APP_ENV: prod
    DATABASE_URL: postgresql+psycopg://blitzball:blitzball_app_password_change_me@blitzball-postgres-postgresql.blitzball.svc.cluster.local:5432/blitzball
    OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318

frontend:
  image: blitzball-frontend
  tag: 0.1.0
  servicePort: 80

ingress:
  enabled: true
  host: ""